name: ffmpeg_kit_audio_flutter
description: The official audio version of a Flutter plugin forked from ffmpeg-kit, supporting iOS and Android.
repository: https://github.com/chenjun1127/ffmpeg_kit_audio_flutter
issue_tracker: https://github.com/chenjun1127/ffmpeg_kit_audio_flutter/issues
homepage: https://github.com/chenjun1127/ffmpeg_kit_audio_flutter
version: 1.0.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.ffmpegkit.flutter
        pluginClass: FFmpegKitFlutterPlugin
      ios:
        pluginClass: FFmpegKitFlutterPlugin
      macos:
        pluginClass: FFmpegKitFlutterPlugin

dependencies:
  ffmpeg_kit_flutter_platform_interface: ^0.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.5
